package rms;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author LubnA
 */
public class CreateAccount extends javax.swing.JFrame {
    
    Connection connect = jconnection.ConnecrDB();
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form CreatAccount
     */
    public CreateAccount() {
        initComponents();
        connect = jconnection.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtfname = new javax.swing.JLabel();
        txtlname = new javax.swing.JLabel();
        txtuname = new javax.swing.JLabel();
        txtphn = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        createaccount = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtfname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtfname.setText("First Name");
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 14, -1, -1));

        txtlname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtlname.setText("Last Name");
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 86, -1, -1));

        txtuname.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtuname.setText("Username");
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 161, -1, -1));

        txtphn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtphn.setText("Phone");
        jPanel1.add(txtphn, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 236, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtemail.setText("Email");
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 313, -1, -1));

        txtpassword1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtpassword1.setText("Password");
        jPanel1.add(txtpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 395, -1, 28));

        firstname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        firstname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 14, 319, 28));

        lastname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 83, 319, 28));

        username.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 158, 319, 28));

        phone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 233, 319, 28));

        email.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 310, 319, 28));

        password.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 396, 319, 28));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 79, 645, 435));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE ACCOUNT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 26, 375, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 14, 73, 25));

        createaccount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createaccount.setText("CREATE");
        createaccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createaccountActionPerformed(evt);
            }
        });
        getContentPane().add(createaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 532, 97, 45));

        Back.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 14, 73, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createaccountActionPerformed
        // TODO add your handling code here:
        
        String sql = "INSERT INTO user (firstname, lastname, username, phone, email, password) VALUES (?, ?, ?, ?, ?, ?)";
        
        try{
            pst = connect.prepareStatement(sql);
            pst.setString(1, firstname.getText());
            pst.setString(2, lastname.getText());
            pst.setString(3, username.getText());
            pst.setString(4, phone.getText());
            pst.setString(5, email.getText());
            pst.setString(6, password.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Create Account Successfully");
            
            firstname.setText(null);
            lastname.setText(null);
            username.setText(null);
            phone.setText(null);
            email.setText(null);
            password.setText(null);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
    }
        
    }//GEN-LAST:event_createaccountActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JButton createaccount;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtfname;
    private javax.swing.JLabel txtlname;
    private javax.swing.JLabel txtpassword1;
    private javax.swing.JLabel txtphn;
    private javax.swing.JLabel txtuname;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
