/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rms;




import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tamim Ahasan
 */
public class ticket extends javax.swing.JFrame {

    
           Connection connect = jconnection.ConnecrDB();
       PreparedStatement pst = null;
       ResultSet rs = null;
/**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
        connect = jconnection.ConnecrDB();
        loadstart();
        loaddestination();
    }
    
    public void loadstart(){
        try{
            pst = connect.prepareStatement("SELECT splace FROM addtrain");
            rs = pst.executeQuery();
            start.removeAllItems();
            
            while(rs.next())
            {
                start.addItem(rs.getString(1));
            }
        }
        catch ( Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void loaddestination(){
        try{
            pst = connect.prepareStatement("SELECT desplace FROM addtrain");
            rs = pst.executeQuery();
            destination.removeAllItems();
            
            while(rs.next())
            {
                destination.addItem(rs.getString(1));
            }
        }
        catch ( Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void load(){
        String startp = start.getSelectedItem().toString();
        String destinationp = destination.getSelectedItem().toString();
        
        try{
            pst= connect.prepareStatement("SELECT * FROM addtrain WHERE splace =? and desplace = ?");
            pst.setString(1, startp);
            pst.setString(2, destinationp);
            rs = pst.executeQuery();
            
            if(rs.next() == true){
                trainname.setText(rs.getString(2));
                trainnumber.setText(rs.getString(1));
                ttprice.setText(rs.getString(5));
            }
            else{
                JOptionPane.showMessageDialog(this, "Not Available");
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        start = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        go = new javax.swing.JButton();
        trainnumber = new javax.swing.JTextField();
        ttprice = new javax.swing.JTextField();
        passangername = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        trainname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numberofseat = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Passanger Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 149, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 131, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Price");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Train Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Train Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 228, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Number of Seats");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 362, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 397, -1, -1));

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 435, 93, 42));

        start.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 48, 250, 35));

        jPanel1.add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 48, 250, 35));

        go.setText("Go");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        jPanel1.add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 48, 90, 35));
        jPanel1.add(trainnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 187, 251, -1));
        jPanel1.add(ttprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 251, -1));
        jPanel1.add(passangername, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 149, 251, -1));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 397, 251, -1));
        jPanel1.add(trainname, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 225, 251, -1));

        jLabel8.setText("Start ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 23, -1, -1));

        jLabel9.setText("Destination");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 23, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 307, -1, -1));

        numberofseat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofseatActionPerformed(evt);
            }
        });
        numberofseat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberofseatKeyPressed(evt);
            }
        });
        jPanel1.add(numberofseat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 359, 251, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 251, -1));

        back.setText("Sign Out");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exit))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        
        String pname = passangername.getText();
        String spalce = start.getSelectedItem().toString();
        String eplace = destination.getSelectedItem().toString();
        String tno = trainnumber.getText();
        String tname = trainname.getText();
        String tprice = ttprice.getText();
        String tdate = date.getText(); 
        String ticket = numberofseat.getText();
        String ttotal = total.getText();
        
        try{
            pst = connect.prepareStatement("INSERT INTO ticket(pname,startp,destp,tnum,tname,price,date,seat,total) VALUES (?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, pname);
            pst.setString(2, spalce);
            pst.setString(3, eplace);
            pst.setString(4, tno);
            pst.setString(5, tname);
            pst.setString(6, tprice);
            pst.setString(7, tdate);
            pst.setString(8, ticket);
            pst.setString(9, ttotal);
            int k = pst.executeUpdate();
            
            if(k == 1){
                JOptionPane.showMessageDialog(this, "Ticket Booked");
                
                passangername.setText("");
                trainnumber.setText("");
                ttprice.setText("");
                total.setText("");
                numberofseat.setText("");
                trainnumber.setText("");
                total.setText("");
                trainname.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this, "Try Again");
            }
            
            //pname,startp,destp,tnum,tname,price,date,seat,total
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_confirmActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_goActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_startActionPerformed

    private void numberofseatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofseatActionPerformed
        // TODO add your handling code here:
           int price, ticket,totn;
        
//        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
//        {
//            price = Integer.parseInt(ttprice.getText());
//            ticket = Integer.parseInt(numberofseat.getText());
//            
//            totn = price * ticket;
//            
//            total.setText(String.valueOf(totn));
//        }
        
    }//GEN-LAST:event_numberofseatActionPerformed

    private void numberofseatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberofseatKeyPressed
        // TODO add your handling code here:
        
        int price, ticket,totn;
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            price = Integer.parseInt(ttprice.getText());
            ticket = Integer.parseInt(numberofseat.getText());
            
            totn = price * ticket;
            
            total.setText(String.valueOf(totn));
        }
    }//GEN-LAST:event_numberofseatKeyPressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton exit;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField numberofseat;
    private javax.swing.JTextField passangername;
    private javax.swing.JComboBox<String> start;
    private javax.swing.JTextField total;
    private javax.swing.JTextField trainname;
    private javax.swing.JTextField trainnumber;
    private javax.swing.JTextField ttprice;
    // End of variables declaration//GEN-END:variables
}
